# Generated by Django 6.0.6 on 2026-06-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_priority_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('3', 'Low'), ('2', 'Medium'), ('1', 'High')], default='Medium', max_length=10),
        ),
    ]
